package main;


import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;


public class DashBoard extends javax.swing.JFrame {
Connection con = null;
    PreparedStatement pre = null;
    ResultSet res = null;
    static String NAME;
    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
        con=Connect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        combtn = new javax.swing.JButton();
        salebtn = new javax.swing.JButton();
        medibtn = new javax.swing.JButton();
        stockbtn1 = new javax.swing.JButton();
        rolebtn1 = new javax.swing.JButton();
        Patientbtn1 = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Model Pharmacy");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 80, 320, 29);

        combtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        combtn.setText("Company");
        combtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combtnActionPerformed(evt);
            }
        });
        getContentPane().add(combtn);
        combtn.setBounds(80, 110, 170, 50);

        salebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        salebtn.setText("Sales");
        salebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salebtnActionPerformed(evt);
            }
        });
        getContentPane().add(salebtn);
        salebtn.setBounds(820, 110, 170, 50);

        medibtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        medibtn.setText("Stock");
        medibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medibtnActionPerformed(evt);
            }
        });
        getContentPane().add(medibtn);
        medibtn.setBounds(90, 560, 170, 50);

        stockbtn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        stockbtn1.setText("Medicine");
        stockbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockbtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(stockbtn1);
        stockbtn1.setBounds(90, 350, 170, 50);

        rolebtn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rolebtn1.setText("Role");
        rolebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolebtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(rolebtn1);
        rolebtn1.setBounds(840, 550, 170, 50);

        Patientbtn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Patientbtn1.setText("Patient");
        Patientbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Patientbtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(Patientbtn1);
        Patientbtn1.setBounds(830, 350, 170, 50);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(971, 20, 100, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel2.setText("Welcome To");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(470, 20, 170, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Sales History");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(480, 560, 160, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salebtnActionPerformed
         new Sales().setVisible(true);
    }//GEN-LAST:event_salebtnActionPerformed

    private void stockbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockbtn1ActionPerformed
        new Medicine().setVisible(true);
    }//GEN-LAST:event_stockbtn1ActionPerformed

    private void rolebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolebtn1ActionPerformed
        new Roles().setVisible(true);
    }//GEN-LAST:event_rolebtn1ActionPerformed

    private void Patientbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patientbtn1ActionPerformed
        new Patient().setVisible(true);
    }//GEN-LAST:event_Patientbtn1ActionPerformed

    private void combtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combtnActionPerformed
        close();
        Company com=new Company();
        com.setVisible(true);
        //new DashBoard().setVisible(false);
        
    }//GEN-LAST:event_combtnActionPerformed

    private void medibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medibtnActionPerformed
       new Stock().setVisible(true);
    }//GEN-LAST:event_medibtnActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
       //exit(0);
      System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new shistory().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new DashBoard().setVisible(true);
            }
        });
    }
    
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Patientbtn1;
    private javax.swing.JButton combtn;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton medibtn;
    private javax.swing.JButton rolebtn1;
    private javax.swing.JButton salebtn;
    private javax.swing.JButton stockbtn1;
    // End of variables declaration//GEN-END:variables

    
    
}
